### ISSUE TITLE
std::optional in fields

### ISSUE THREAD

**Issue by LawlietRyuzaki** [apolukhin/magic_get#15]
```c++
#include <optional>
#include <boost/pfr.hpp>

struct Foo {
    std::optional<int> a;
};

int main() {
    Foo f{5};
    boost::pfr::get<0>(f);
}
```

Is there any way to compile this code?

I compiled with gcc 6.3 and gcc 7.1 and get the following errors:
`error: conversion from 'boost::pfr::detail::loophole_ubiq<Foo, 0>' to 'std::optional<int>' is ambiguous
     : sequence_tuple::tuple< decltype(T{ loophole_ubiq<T, I>{}... }, 0) > // Instantiating loopholes.`

**Comment by apolukhin** [comment]
Fixed the issue! Thanks for providing the test case.
