### ISSUE TITLE
Functions in core17_generated.hpp

### ISSUE THREAD

**Issue by shaochun** [apolukhin/magic_get#25]
How are the functions generated in `core17_generated.hpp`?

Are they generated by hand or by some tools?

    https://github.com/apolukhin/magic_get/blob/develop/include/boost/pfr/detail/core17_generated.hpp

**Comment by apolukhin** [comment]
Those are generated by the Python script https://github.com/apolukhin/magic_get/blob/develop/misc/generate_cpp17.py

I have to add that info into the generated file. Thanks for the heads up!

**Comment by shaochun** [comment]
Thanks!
