### ISSUE TITLE
What about unique_ptr?

### ISSUE THREAD

**Issue by filcuc** [apolukhin/magic_get#27]

**Comment by apolukhin** [comment]
Could you please provide a test case that does not work, along with compiler version and flags?

**Comment by filcuc** [comment]
Yes, but basically the library reject the introspection of a struct with an unique_ptr because a static assert request every field to be copy constructable

**Comment by filcuc** [comment]
```
#include <memory>
#include <boost/pfr.hpp>

struct Message {
  std::unique_ptr<int> data;
};

int main(int argc, char* argv[]) {
  Message message;
  auto& ptr = boost::pfr::get<0>(message);
  return 0;
}

```

**Comment by filcuc** [comment]
arm-poky-linux-gnueabi-g++ (GCC) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by filcuc** [comment]
```
Linux sdevvs4n02 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by filcuc** [comment]
@apolukhin do you need more information?

**Comment by filcuc** [comment]
@apolukhin feel free to close this issue if you think that it's not solvable

**Comment by filcuc** [comment]
@apolukhin if is simple for you please share the patches for supporting move only types..they can be usefull for me

**Comment by apolukhin** [comment]
Just comment out this line https://github.com/apolukhin/magic_get/blob/c5130dd9e5f52d31bf32d3e93cbc728686a5f4be/include/boost/pfr/detail/fields_count.hpp#L33 and uncomment the following one. You'll have to comment out the static_assert for is_copyable too.

**Comment by apolukhin** [comment]
Looks like I've found a way to support move only types or references/copyables at the same time. It's not perfect, you can not have a reference and a unique_ptr at the same time.

I'll write some tests and push the changes into develop in a few days.

**Comment by apolukhin** [comment]
@filcuc I've just merged the required patches to develop. Please test, and if there's no issues (or there's no objections in 3 days) I'll merge it to master branch.

**Comment by apolukhin** [comment]
No complains so far :)
