### ISSUE TITLE
Is it possible to fix the primitive types only limitation?

### ISSUE THREAD

**Issue by aminroosta** [apolukhin/magic_get#3]
@apolukhin @AntonBikineev
I've been trying to somehow overcome the limitation for types for a couple of days!
Here is my failed attempt explained on stackoverflow ( [How to make C++ ADL to look into all instances of a template?](http://stackoverflow.com/questions/40008554/how-to-make-c-adl-to-look-into-all-instances-of-a-template) ).

I have a feeling that there might be a way to do this (it's stopping me from going to sleep every night 😞 ). Please take look at my question, maybe you guys could find something i couldn't see.

**Comment by apolukhin** [comment]
I've already tried to walk that way and failed to reach success :(

Maybe I've missed something, but I'm definitely not going to start playing with friend functions again in the nearest future.

**Comment by aminroosta** [comment]
@apolukhin Someone found a [solution](http://stackoverflow.com/questions/40008554/how-to-make-c-adl-to-look-into-all-instances-of-a-template?noredirect=1#comment67658618_40008554) and It's really amazing ❤️ 😃 

BUT only works after gcc 5.2, clang 3.5.1 - 3.7.1

**Comment by brunocodutra** [comment]
@aminroosta If I understand it correctly, the snippet I posted on #5 should achieve what you seek

**Comment by apolukhin** [comment]
Solution is integrated into the library :) Limitation removed: non-flat functions work with any aggregate initializable function.
