### ISSUE TITLE
vs2019 bulid error ..

### ISSUE THREAD

**Issue by bilbilemm** [apolukhin/magic_get#42]
Visual Studio 2019 (v142)
error C2338: ====================> Boost.PFR: Types with user specified constructors (non-aggregate initializable types) are not supported.
查看对正在编译的函数 模板 实例化“size_t boost::pfr::detail::fields_count<Type>(void) noexcept”的引用
------------------------------------------------------------------------------------------------------
struct msg_HelperStr {
	HelperStrType	_HelperType;
	std::string		_HelperStr;
};

**Comment by bilbilemm** [comment]
enum HelperStrType {
	helper_normal,					//正常
	helper_error,					//异常
};

**Comment by apolukhin** [comment]
With what /std flag are you building? /std:c++17 ?

**Comment by spudwa** [comment]
If your using VS2019 it supports spaceship operator :-)
https://devblogs.microsoft.com/cppblog/simplify-your-code-with-rocket-science-c20s-spaceship-operator/

**Comment by bilbilemm** [comment]
> 使用什么/ std标志构建？/ std：c ++ 17？

 

> With what /std flag are you building? /std:c++17 ?
Sorry.. I used it. /std:c++latest。Will you update this project? This project is very good,Gave me a lot of help。 thank you
